# Copyright 2024 The Pigweed Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

package(default_visibility = ["//visibility:public"])

exports_files(["wifi_config.h"])

cc_library(
    name = "config",
    srcs = [
        "board.c",
        "clock_config.c",
        "peripherals.c",
        "pin_mux.c",
        "wifi_bt_config.c",
        "app_bluetooth_config.h",
    ],
    hdrs = [
        "wifi_bt_config.h",
        "wifi_bt_module_config.h",
        "wifi_config.h",
        "ffconf.h",
        "usb_host_config.h",
        "sdmmc_config.h",
        "board.h",
        "clock_config.h",
        "peripherals.h",
        "pin_mux.h",
    ],
    copts = [
        "-include", "$(location app_bluetooth_config.h)",
        "-Wno-cast-qual",
    ],
    includes = [
        ".",
    ],
    target_compatible_with = [
        "//pw_build/constraints/board:mimxrt595_evk",
        "//pw_build/constraints/rtos:freertos",
        "@platforms//cpu:armv8-m",
    ],
    deps = [
        "//pw_preprocessor",
        "@mcuxpresso//:platform.drivers.lpc_gpio.MIMXRT595S",
        "@mcuxpresso//:component.rt_gpio_adapter.MIMXRT595S",
        "@mcuxpresso//:utility.debug_console.MIMXRT595S",
        "@mcuxpresso//:platform.drivers.power.MIMXRT595S",
        "@mcuxpresso//:platform.drivers.lpc_iopctl.MIMXRT595S",
        "@mcuxpresso//:middleware.sdmmc.host.usdhc.MIMXRT595S",
        "@mcuxpresso//:middleware.sdmmc.osa.freertos.MIMXRT595S",
        "@mcuxpresso//:platform.drivers.usdhc.MIMXRT595S",
        "@mcuxpresso//:middleware.sdmmc.common.MIMXRT595S",
        "@mcuxpresso//:platform.drivers.flexspi.MIMXRT595S",
        "@mcuxpresso//:platform.drivers.cache_cache64.MIMXRT595S",
        "@mcuxpresso//:middleware.sdmmc.sdio.MIMXRT595S",
        "@mcuxpresso//:platform.drivers.flexcomm_i2c.MIMXRT595S",
        "@mcuxpresso//:platform.drivers.i3c.MIMXRT595S",
    ],
    alwayslink = 1,
)
